name = "hexo-sharp"
type = "javascript"
zone_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-04"

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

[site]
bucket = './dist'
entry-point = './'
exclude = ["worker.js", "worker.js.map"]

# [secrets]
# JWT_SECRET

[miniflare]
kv_persist = true

[miniflare.globals]
JWT_SECRET = "1145141919810"
