name = "hexo-sharp"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-17"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
dir = "dist"
main = "./worker.js"

[site]
bucket = './dist'
entry-point = './dist/worker.js'
