name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Replace the KV namespace
        run: sed -i 's/PRESERVED_FOR_ACTIONS/${{ secrets.KV_ID }}/g' wrangler.toml
      - name: Publish
        uses: lixiang810/wrangler-action@1.4.0-node16
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            corepack enable
            pnpm install
            pnpm cleanupAssets
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
