name: Merge-upstream

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: lixiang810/HexoSharp
          upstream-branch: main
          branch: main
          token: ${{ secrets.GH_TOKEN }}
